#pragma once

#define RING0_CALCULATOR_DEVICE	0x8000

#define RING0_CALCULATOR_ADD			CTL_CODE(RING0_CALCULATOR_DEVICE, 0x800, METHOD_NEITHER, FILE_ANY_ACCESS)
#define RING0_CALCULATOR_MINUS			CTL_CODE(RING0_CALCULATOR_DEVICE, 0x801, METHOD_NEITHER, FILE_ANY_ACCESS)
#define RING0_CALCULATOR_MUL			CTL_CODE(RING0_CALCULATOR_DEVICE, 0x803, METHOD_NEITHER, FILE_ANY_ACCESS)
#define RING0_CALCULATOR_DIV			CTL_CODE(RING0_CALCULATOR_DEVICE, 0x804, METHOD_NEITHER, FILE_ANY_ACCESS)